name: Automatic Batch Conversion
run-name: ${{github.actor}} started a batch conversion job.
on: push
jobs:
  Batch-Convert:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '|NoConvert|')"
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v3
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install MuseScore 3
        run: |
          Invoke-WebRequest -URI https://github.com/musescore/MuseScore/releases/download/v3.6.2/MuseScore-3.6.2.548021803-x86_64.msi -OutFile MuseScore3Installer.msi
          .\MuseScore3Installer.msi -q
      - name: Install MuseScore 4
        run: |
          Invoke-WebRequest -URI https://github.com/musescore/MuseScore/releases/download/v4.0.1/MuseScore-4.0.1.230121751-x86_64.msi -OutFile MuseScore4Installer.msi
          .\MuseScore4Installer.msi -q
      - name: Install MIDIflip (NodeJS)
        run: npm install https://github.com/ThePython10110/midiflip
      - name: Convert!
        run: python batch_convert.py --auto --output Converted
      - name: Commit to git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>" #No idea whether this will work, but I looked it up...
          git add .
          git commit -m "Automatic conversion |NoConvert|"
          git push
