name: Automatic Batch Conversion
run-name: ${{github.actor}} started a batch conversion job.
on: push
jobs:
  Batch-Convert:
    runs-on: windows-latest
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v3
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install Winget
        run: $ProgressPreference='Silent'
      - run: Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.3.2691/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile .\MicrosoftDesktopAppInstaller_8wekyb3d8bbwe.msixbundle
      - run: Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
      - run: Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
      - run: Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
      - name: Install MuseScore
        run: winget install musescore --version 3.6.2.548021803 #So much less work than what I was doing before...
      - name: Install MIDIflip (NodeJS)
        run: npm install midiflip
      - name: Convert!
        run: python batch_convert.py