name: Batch Convert Github Actions Test
run-name: ${{github.actor}} started a batch convert.
on: [push]
jobs:
  Convert:
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v3
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add universe to apt just in case
        run: sudo apt-add-repository universe
      - name: Update apt
        run: sudo apt update
      - name: Install various apt packages so MuseScore works
        run: sudo apt install libportaudio2 libportmidi-dev libpulse-dev libqt5quick5 libqt5xml5 libqt5xmlpatterns5 libqt5printsupport5 libqt5help5 qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools #Why does this need QT? It doesn't have to load the GUI.
      - name: Install MuseScore (Snap)
        run: sudo snap install musescore
      #- run: export $PATH="/snap/musescore/228/usr/bin:$PATH" #Not sure why this isn't working...
      - name: Install MIDIflip (NodeJS)
        run: npm install midiflip
      - name: Prepare JSON file
        run: python batch_convert_linux.py
      - name: Convert MuseScore files
        run: /snap/musescore/228/usr/bin/mscore -j convert_job3.json #So I'm using the absolute path.
      - name: MIDIflip
        run: midiflip midiflip -i "./MIDI/**/*.midi" -o "Output/FlippedMIDI"
